services:
  mongo:
    image: mongo:8.0-noble
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE:-appdb}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-example}"
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      # Beispiel: mongodb://<user>:<pass>@mongo:27017/<dbname>?authSource=admin
      MONGO_URI: "${MONGO_URI:-mongodb://root:example@mongo:27017/appdb?authSource=admin}"
      PORT: "${PORT:-3000}"
      NODE_ENV: "${NODE_ENV:-production}"
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000/health"]
      interval: 20s
      timeout: 5s
      retries: 3

volumes:
  mongo_data:
